/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103x6.h"
#include "GPIO.h"

void Clock_INIT()
{
	//Enable Clock GPIOA
	RCC_GPIOA_CLK_EN();

	//Enable Clock GPIOB
	RCC_GPIOB_CLK_EN();
}

void GPIO_INIT()
{
	PIN_CONFIG pin_config;

	//make PORTA PIN1 input floating
	pin_config.PIN_NUM = PIN_NUM_1;
	pin_config.PIN_OUT_SPEED = PIN_SPEED_RESET;
	pin_config.PIN_MODE = PIN_MODE_IN_FLO;

	MCAL_GPIO_Init(GPIOA, &pin_config);

	//make PORTA PIN13 input floating
	pin_config.PIN_NUM = PIN_NUM_13;
	pin_config.PIN_OUT_SPEED = PIN_SPEED_RESET;
	pin_config.PIN_MODE = PIN_MODE_IN_FLO;

	MCAL_GPIO_Init(GPIOA, &pin_config);



	//make PORTB PIN1 output with max 10 MHZ Push-Pull
	pin_config.PIN_NUM = PIN_NUM_1;
	pin_config.PIN_OUT_SPEED = PIN_SPEED_10MHZ;
	pin_config.PIN_MODE = PIN_MODE_OUT_PP;

	MCAL_GPIO_Init(GPIOB, &pin_config);

	//make PORTB PIN13 output with max 10 MHZ Push-Pull
	pin_config.PIN_NUM = PIN_NUM_13;
	pin_config.PIN_OUT_SPEED = PIN_SPEED_10MHZ;
	pin_config.PIN_MODE = PIN_MODE_OUT_PP;

	MCAL_GPIO_Init(GPIOB, &pin_config);

}

int main(void)
{
	//initiation
	Clock_INIT();
	GPIO_INIT();
	volatile uint32_t flag = 1;

	while(1)
	{
		if((MCAL_GPIO_READ_PIN(GPIOA, PIN_NUM_1) == 0) && flag)
		{
			MCAL_GPIO_TOGGLE_PIN(GPIOB, PIN_NUM_1);
			flag = 0;
		}
		if(MCAL_GPIO_READ_PIN(GPIOA, PIN_NUM_1))
		{
			flag = 1;
		}
		if(MCAL_GPIO_READ_PIN(GPIOA, PIN_NUM_13))
		{
			MCAL_GPIO_TOGGLE_PIN(GPIOB, PIN_NUM_13);
		}
		for(volatile int i = 0;i<2000;i++);
	}
}
