/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>

//RCC
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *((volatile uint32_t *)(RCC_BASE + 0x18))
#define RCC_CFGR *((volatile uint32_t *)(RCC_BASE + 0x04))
#define RCC_CR *((volatile uint32_t *)(RCC_BASE + 0x00))

//GPIO
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *((volatile uint32_t *)(GPIOA_BASE + 0x04))
#define GPIOA_ODR *((volatile uint32_t *)(GPIOA_BASE + 0x0C))
#define GPIOA_CRL *((volatile uint32_t *)(GPIOA_BASE + 0x00))

//AFIO
#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1 *((volatile uint32_t *)(AFIO_BASE + 0x08))

//EXTI
#define EXTI_BASE 0x40010400
#define EXTI_IMR *((volatile uint32_t *)(EXTI_BASE + 0x00))
#define EXTI_PR *((volatile uint32_t *)(EXTI_BASE + 0x14))
#define EXTI_RTSR *((volatile uint32_t *)(EXTI_BASE + 0x08))


//NVIC
#define NVIC_ISER0 *((volatile uint32_t *)(0xE000E100))

//Bit manipulation
#define SETBIT(reg,bit) reg|=(1<<bit)
#define CLRBIT(reg,bit) reg&=~(1<<bit)
#define TGLBIT(reg,bit) reg^=(1<<bit)

void Clock_INIT()
{
	//enable clock for GPIO port A
	SETBIT(RCC_APB2ENR,2);

	//enable clock for AFIO
	SETBIT(RCC_APB2ENR,0);
}

void GPIO_INIT()
{
	//make PIN 13 port A output
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;

	//make PIN 0 Port A input
	SETBIT(GPIOA_CRL,2);
}

void EXTI_INIT()
{
	//enable interrupt mask
	SETBIT(EXTI_IMR,0);

	//enable Rising trigger selection register
	SETBIT(EXTI_RTSR,0);

	//enable NVCI for EXTI0 in TRQ 6
	SETBIT(NVIC_ISER0,6);
}

void AFIO_INIT()
{
	//enable PORT A as the sourse of EXTI0
	CLRBIT(AFIO_EXTICR1,0);
}

int main(void)
{
	Clock_INIT();
	GPIO_INIT();
	AFIO_INIT();
	EXTI_INIT();

	/* Loop forever */
	while(1);
}

void EXTI0_IRQHandler(void)
{
	//toggle the led
	TGLBIT(GPIOA_ODR,13);

	//put 1 to delete this interrupt as it is handled
	SETBIT(EXTI_PR,0);
}

