/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>

//RCC registers
#define RCC_BASE 0x40021000
#define RCC_APB2ENR (*(volatile uint32_t *)(RCC_BASE + 0x18))

//GPIOA
#define GPIOA_BASE 0x40010800
#define GPIOA_CRL (*(volatile uint32_t *)(GPIOA_BASE + 0x00))
#define GPIOA_CRH (*(volatile uint32_t *)(GPIOA_BASE + 0x04))
#define GPIOA_IDR (*(volatile uint32_t *)(GPIOA_BASE + 0x08))

//GPIOB
#define GPIOB_BASE 0x40010C00
#define GPIOB_CRL (*(volatile uint32_t *)(GPIOB_BASE + 0x00))
#define GPIOB_CRH (*(volatile uint32_t *)(GPIOB_BASE + 0x04))
#define GPIOB_ODR (*(volatile uint32_t *)(GPIOB_BASE + 0x0C))

//BitMasks
#define SETBIT(reg,bit) reg|=(1<<bit)
#define CLRBIT(reg,bit) reg&=~(1<<bit)
#define GETBIT(reg,bit) ((reg>>bit)&1)
#define TGLBIT(reg,bit) reg^=(1<<bit)

void GPIO_INIT()
{
	//make PORTA PIN1 input
	CLRBIT(GPIOA_CRL,4);
	CLRBIT(GPIOA_CRL,5);

	//make PORTA PIN1 floating
	SETBIT(GPIOA_CRL,6);
	CLRBIT(GPIOA_CRL,7);

	//make PORTA PIN13 input
	CLRBIT(GPIOA_CRH,20);
	CLRBIT(GPIOA_CRH,21);

	//make PORTA PIN13 floating
	SETBIT(GPIOA_CRH,22);
	CLRBIT(GPIOA_CRH,23);

	//make PORTB PIN1 output with max 10 MHZ
	SETBIT(GPIOB_CRL,4);
	CLRBIT(GPIOB_CRL,5);

	//make PORTB PIN1 Push-Pull
	CLRBIT(GPIOB_CRL,6);
	CLRBIT(GPIOB_CRL,7);

	//make PORTB PIN13 output with max 10 MHZ
	SETBIT(GPIOB_CRH,20);
	CLRBIT(GPIOB_CRH,21);

	//make PORTB PIN13 Push-Pull
	CLRBIT(GPIOB_CRH,22);
	CLRBIT(GPIOB_CRH,23);

}

void Clock_INIT()
{
	/*Bit 2 IOPARST: IO port A reset
	Set and cleared by software.
	0: No effect
	1: Reset IO port A*/
	SETBIT(RCC_APB2ENR,2);

	/*Bit 3 IOPBRST: IO port B reset
	Set and cleared by software.
	0: No effect
	1: Reset IO port B*/
	SETBIT(RCC_APB2ENR,3);
}


int main(void)
{
	//initiation
	Clock_INIT();
	GPIO_INIT();
	volatile uint32_t flag = 1;

	while(1)
	{
		if((GETBIT(GPIOA_IDR,1) == 0)&&flag)
		{
			TGLBIT(GPIOB_ODR,1);
			flag = 0;
		}
		if(GETBIT(GPIOA_IDR,1) != 0)
		{
			flag = 1;
		}
		if((GETBIT(GPIOA_IDR,13) == 1))
		{
			TGLBIT(GPIOB_ODR,13);
		}
		for(volatile int i = 0;i<2000;i++);
	}
}
